version: '3'
services:
  web1:
    image: quay.io/kalote/companyctf_sql1:1.0
    ports:
      - "5000:80"
    depends_on: 
      - mysql
  
  web2:
    image: quay.io/kalote/companyctf_sql2:1.0
    ports:
      - "5001:80"
    depends_on: 
      - mysql

  web3:
    image: quay.io/kalote/companyctf_sql3:1.0
    ports:
      - "5002:80"
    depends_on: 
      - mysql
  
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: d4p4ssw0rd1
      MYSQL_USER: ctfsql
      MYSQL_PASSWORD: d4dbp4ssw0rd1
      MYSQL_DATABASE: ctfsql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
