apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-jwt-vuln
  name: custom-jwt-vuln
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-jwt-vuln
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-jwt-vuln
  name: custom-jwt-vuln
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-jwt-vuln
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-jwt-vuln
    spec:
      containers:
      - name: custom-jwt-vuln
        env:
        - name: FLAG
          value: 'ses-ctf{jwt15funeverytim3}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-jwt-vuln
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-jwt-rs256
  name: custom-jwt-rs256
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-jwt-rs256
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-jwt-rs256
  name: custom-jwt-rs256
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-jwt-rs256
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-jwt-rs256
    spec:
      containers:
      - name: custom-jwt-rs256
        env:
        - name: FLAG
          value: 'ses-ctf{jwtw1thrs25615v3ryfun}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-jwt-vuln-rs256
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-fun-qrcode
  name: custom-fun-qrcode
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-fun-qrcode
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-fun-qrcode
  name: custom-fun-qrcode
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-fun-qrcode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-fun-qrcode
    spec:
      containers:
      - name: custom-fun-qrcode
        env:
        - name: FLAG
          value: 'ses-ctf{qrc0d34ndCTF1salw4ysg00d}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-fun-qrcode
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-log-metrics
  name: custom-log-metrics
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-log-metrics
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-log-metrics
  name: custom-log-metrics
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-log-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-log-metrics
    spec:
      containers:
      - name: custom-log-metrics
        env:
        - name: FLAG
          value: 'ses-ctf{l0gm3tr1cs4regr34tn0rm4lly}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-logs-metrics-flag
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-deserialize
  name: custom-deserialize
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-deserialize
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-deserialize
  name: custom-deserialize
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-deserialize
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-deserialize
    spec:
      containers:
      - name: custom-deserialize
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-deserialize-vuln
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-j-mystery
  name: custom-j-mystery
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-j-mystery
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-j-mystery
  name: custom-j-mystery
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-j-mystery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-j-mystery
    spec:
      containers:
      - name: custom-j-mystery
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-j-mystery
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: custom-template-pug
  name: custom-template-pug
  namespace: custom-challenges
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: custom-template-pug
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: custom-template-pug
  name: custom-template-pug
  namespace: custom-challenges
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-template-pug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-template-pug
    spec:
      containers:
      - name: custom-template-pug
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        image: quay.io/jonathan_vacherat/axa-ses-2021-ctf-template-pug-vuln
