version: '3'
services:
  web1:
    build:
      context: ../SQL1
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ../SQL1/src:/var/www/html/
    depends_on: 
      - mysql
  
  web2:
    build:
      context: ../SQL2
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ../SQL2/src:/var/www/html/
    depends_on: 
      - mysql

  web3:
    build:
      context: ../SQL3
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    volumes:
      - ../SQL3/src:/var/www/html/
    depends_on: 
      - mysql
  
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: d4p4ssw0rd1
      MYSQL_USER: ctfsql
      MYSQL_PASSWORD: d4dbp4ssw0rd1
      MYSQL_DATABASE: ctfsql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
